### ISSUE TITLE
Don't include logback

### ISSUE THREAD

**Issue by Schaka** [sparsick/testcontainers-git#158]
It seems right now, logback implementations are packaged into your jar.
As a result, my project ends up pulling them and they need to be explicitly excluded to not conflict with log4j2.

I'd recommend just including the slf4j interfaces instead

**Comment by sparsick** [comment]
Thanks for the hint. I will have a look on it after my vacation.

**Comment by sparsick** [comment]
@Schaka  I changed the dependency scope to provided so that you should not have the conflict with log4j2
