### ISSUE TITLE
ssh auth failed due to wrong permission of authorized_keys

### ISSUE THREAD

**Issue by maddingo** [sparsick/testcontainers-git#70]
I get this error in the container logs:
`
Authentication refused: bad ownership or modes for file /home/git/.ssh/authorized_keys
Received disconnect from 172.17.0.1 port 53148:3: com.jcraft.jsch.JSchException: Auth fail [preauth]
`
The file permissions at the moment are `-rw-rw-r--`.
Modifying them to 600 fixes the problem

**Comment by sparsick** [comment]
Fixes in release 0.6.0
